pipeline {
    agent {
        label 'php-agent'
    }
    
    stages {
        stage('Checkout') {
            steps {
                checkout scm
                echo 'Repository cloned successfully'
            }
        }
        
        stage('List Files') {
            steps {
                echo 'Listing project files...'
                sh 'ls -la lab04/php_arrays/'
            }
        }
        
        stage('Simple PHP Check') {
            steps {
                echo 'Running basic PHP checks...'
                dir('lab04/php_arrays') {
                    sh 'php -v'
                    sh 'php -l public/index.php'
                    sh 'php -l public/simple_tests.php'
                }
            }
        }
        
        stage('Run Tests') {
            steps {
                echo 'Running tests...'
                dir('lab04/php_arrays') {
                    sh 'php public/simple_tests.php'
                }
            }
        }
    }
    
    post {
        always {
            echo 'Pipeline completed'
        }
        success {
            echo ' SUCCESS!'
        }
        failure {
            echo ' FAILED!'
        }
    }
}