
FROM jenkins/ssh-agent:alpine

USER root

# Обновляем репозитории и ставим PHP 8.3 + Composer
RUN apk update && \
    apk add --no-cache \
    php83 \
    php83-mbstring \
    php83-xml \
    php83-bcmath \
    php83-tokenizer \
    php83-pecl-xdebug \
    php83-opcache \
    composer \
    git \
    bash

# Делаем php и composer доступными по команде php/composer (а не php83)
RUN ln -s /usr/bin/php83 /usr/bin/php && \
    ln -s /usr/bin/composer83 /usr/bin/composer || true

# Добавляем публичный ключ Jenkins (чтобы Jenkins мог подключиться)
RUN mkdir -p /home/jenkins/.ssh
COPY secrets/jenkins_to_agents.pub /home/jenkins/.ssh/authorized_keys
RUN chown -R jenkins:jenkins /home/jenkins/.ssh && \
    chmod 700 /home/jenkins/.ssh && \
    chmod 600 /home/jenkins/.ssh/authorized_keys

# Возвращаемся к пользователю jenkins
USER jenkins
WORKDIR /home/jenkins

EXPOSE 22
CMD ["/usr/sbin/sshd", "-D"]